repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: check-merge-conflict

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.10
      - id: black-jupyter
        language_version: python3.10

  - repo: local
    hooks:
      - id: ruff
        name: ruff
        language: python
        types: [python]
        entry: ruff check --no-cache --fix
