repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-merge-conflict

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.4.2
    hooks:
      - id: black
        name: black
        entry: black
        language: python
      - id: black-jupyter
        name: black-jupyter
        entry: black
        language: python

  - repo: local
    hooks:
      - id: ruff
        name: ruff
        language: python
        types: [python]
        entry: ruff check --no-cache --fix
