# This workflow will install Python dependencies, run code-quality checks

name: code-quality

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install pre-commit
      run: |
        pip install pre-commit
        pre-commit install

    - name: Run code-quality checks
      run: SKIP=mypy pre-commit run --all-files
